server {
    listen 8080;
    server_name localhost;
    root www;
    index index.html;
    client_max_body_size 10;
    error_page 404 /erreurs/404.html;

    location /readonly {
        allow_methods GET;
    }

    location /files {
        root storage;
        allow_methods GET;
        autoindex on;
    }

    location /old {
        return http://localhost:8080/;
    }

    location /uploads {
        root .;
        allow_methods GET;
    }

    location /upload {
        root images;
        allow_methods POST DELETE;
        upload uploads;
    }

    location /cgi-bin {
        cgi .py /usr/bin/python3;
    }
}

server {
    listen 9090;
    server_name audi;
    root www2;
    index index.html;
}