server {
    listen 8080;
    server_name localhost;
    root www;
    index index.html;
    client_max_body_size 1000000;
    error_page 404 /erreurs/404.html;

    location /upload {
        allow_methods POST DELETE;
        upload /var/uploads;
    }

    location /images {
        allow_methods GET;
        autoindex on;
    }
}